// Drives the claim page in Chromium with a virtual WebAuthn authenticator (a real passkey flow, no human):
// open link → check award card → create passkey → sponsored claim → receipt. Screenshots at 390 and 1280.
// Usage: node scripts/web-claim.mjs <claim-link> [outDir]
import { chromium } from 'playwright'
import { mkdirSync } from 'node:fs'
const [link, out = 'docs/ui'] = process.argv.slice(2)
mkdirSync(out, { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'ko-KR', deviceScaleFactor: 2 })
const page = await ctx.newPage()
const cdp = await ctx.newCDPSession(page)
await cdp.send('WebAuthn.enable')
await cdp.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } })
page.on('console', (m) => console.log('[page]', m.text()))
await page.goto(link)
await page.waitForSelector('.amount')
await page.screenshot({ path: `${out}/claim-390.png` })
const t0 = Date.now()
await page.click('#cta')
await page.waitForSelector('text=Received', { timeout: 60000 })
console.log(JSON.stringify({ claimSeconds: (Date.now() - t0) / 1000, amount: await page.textContent('.amount'), unit: await page.textContent('.unit'), local: await page.textContent('.local').catch(() => null) }))
await page.screenshot({ path: `${out}/receipt-390.png` })
await page.click('summary')
await page.screenshot({ path: `${out}/receipt-details-390.png`, fullPage: true })
const tx = await page.getAttribute('dd a', 'href')
console.log('tx', tx)
const wide = await browser.newPage({ viewport: { width: 1280, height: 800 } })
await wide.goto(new URL('/', link).toString())
await wide.waitForSelector('tbody tr')
await wide.screenshot({ path: `${out}/ops-1280.png` })
const narrow = await browser.newPage({ viewport: { width: 390, height: 844 } })
await narrow.goto(new URL('/', link).toString())
await narrow.waitForSelector('tbody tr')
const overflow = await narrow.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
console.log('ops-390 horizontal overflow:', overflow)
await narrow.screenshot({ path: `${out}/ops-390.png` })
await browser.close()
