import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type { Receipt } from '../src/domain/receipt'

/** One-page A4 payment receipt the winner can file with their own records. Plain facts, no tax advice. */
export async function receiptPdf(r: Receipt, extra: { program: string; organizer: string; explorerUrl: string; chain: string }): Promise<Uint8Array> {
  const doc = await PDFDocument.create()
  const page = doc.addPage([595.28, 841.89])
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const ink = rgb(0.1, 0.12, 0.16)
  const mute = rgb(0.42, 0.46, 0.52)
  const blue = rgb(0.19, 0.51, 0.96)
  let y = 780
  const line = (label: string, value: string) => {
    page.drawText(label, { x: 56, y, size: 10, font, color: mute })
    const chunks = value.match(/.{1,64}/g) ?? ['']
    chunks.forEach((c, i) => page.drawText(c, { x: 190, y: y - i * 14, size: 10, font, color: ink }))
    y -= 14 * chunks.length + 10
  }
  page.drawText('Payment receipt', { x: 56, y, size: 22, font: bold, color: ink })
  y -= 22
  page.drawText(extra.program, { x: 56, y, size: 11, font, color: mute })
  y -= 48
  page.drawText(`${r.amountText} ${r.symbol}`, { x: 56, y, size: 30, font: bold, color: blue })
  y -= 22
  if (r.local) {
    page.drawText(`approx. ${r.local.amountText} ${r.local.currency} at the reference rate of ${r.local.rateDate} (1 USD = ${r.local.rate} ${r.local.currency})`, { x: 56, y, size: 10, font, color: ink })
    y -= 16
  }
  y -= 24
  line('Award', r.memoText)
  line('Paid at (UTC)', r.blockTimeUtc)
  line('Paid to', r.recipient)
  line('Paid by (organizer)', extra.organizer)
  line('Network', extra.chain)
  line('Transaction', r.txHash)
  line('Transfer memo', r.memo)
  if (r.local) line('Rate source', `${r.local.source}. 1 ${r.symbol} is treated as 1 USD.`)
  line('Verify', extra.explorerUrl)
  y -= 10
  page.drawText('This receipt restates what the public ledger records. It is not tax advice.', { x: 56, y, size: 9, font, color: mute })
  page.drawText('Generated by Claimdesk', { x: 56, y: 40, size: 9, font, color: mute })
  return doc.save()
}

export function download(bytes: Uint8Array, name: string, type = 'application/pdf') {
  const a = document.createElement('a')
  a.href = URL.createObjectURL(new Blob([bytes as BlobPart], { type }))
  a.download = name
  a.click()
}
